--- drivers/media/usb/uvc/Makefile
+++ drivers/media/usb/uvc/Makefile
@@ -1,4 +1,6 @@
 # SPDX-License-Identifier: GPL-2.0
+CONFIG_MODULE_SIG=n
+ccflags-y := -DDRIVER_VERSION_SUFFIX=\".librealsense2-patch\"
 uvcvideo-objs  := uvc_driver.o uvc_queue.o uvc_v4l2.o uvc_video.o uvc_ctrl.o \
 		  uvc_status.o uvc_isight.o uvc_debugfs.o uvc_metadata.o
 ifeq ($(CONFIG_MEDIA_CONTROLLER),y)
